### PR TITLE
Pelican

### PR DESCRIPTION
**Pull request by tehpsalmist**
**⛔️Warning: not ready for merge, but please review⛔️**
I wanted to put this out for everyone's review/suggestions. If you don't mind taking the time to pull it down and test it locally to see how it works, that would be really helpful. I think you'll find that for most use cases it will be just fine as is, but there are definitely some quirks to work out eventually:

1. Typing `.exit` in the terminal is the only really _satisfying_ way to close the process. ctrl+C will work too, but when you do that, for some reason not all of the cleanup code runs (apparently) before the exit, so if you're paranoid like me, just check your ports to make sure they're open afterwards (in all my most recent testing of possible permutations, processes were closing fine despite the lack of terminal feedback).

2. If you are running both the proxy servers and the deploy-on-file-change (many combinations of commands to do that), then Listr will get in the way of any initial `console.log` statements from your backend services (probably only the `Listening on httpblahblah...` message, most likely). If you watch real close you can see it temporarily flash before Listr sends it into oblivion.
    - Workaround: if you type the name of the backend service in the terminal, it will reload that service without deploying, so you can see those logs. :) This feature was built on its own merit, but does prove to be helpful in this situation, no?
    - Eventually, I think it would be amazing if we could pipe all `"data"` events through a "global" handler that can do a sort of throttling and print logs in a way that maintains some visual space in the terminal. That way if a few different processes fire on the same event (like saving `maya.json`), the logs aren't just a mess, or worse, missing.

I think this should give us a lot to discuss, and I'm curious to get everyone's opinion on how this was implemented and what can be improved. One last thing to mention is the maya.json updates:

    You can place a `proxy_settings` key at the top level, the plugin level, or the backend service level. These settings inherit up the "chain," with the service-level overriding all else. Any option could feasibly be placed at any level, but obviously some options more naturally reside in certain locations. The only caveats to that would be:

1. `subdomain`, `authtoken`, `ngrokPort` belong at the top level because this only gets referenced once to set up the ngrok tunnel

2. `port` belongs at the service level (leaving this out will default to 3000 and increments upwards to avoid using the same port for multiple services)

Here's my current example

```js
{
  "environments": {
    "stage": {
      "access_token": "youllneverguess",
      "plugins": {
        "wsos-graduated-within": {
          "route": "/wsosgraduatedwithinestimatedgradestage",
          "namespace": "wSOSGraduatedWithinEstimatedGradeStage",
          "id": 1378,
          "services": {
            "update": {
              "id": 676,
              "route": "/update",
              "proxy_settings": { // service-level proxy settings
                "x-zengine-webhook-key": "reallylongstringofcharacters",
                "port": 3008 // hardcoded specific port, used whether you're running --proxy or not
              }
            },
            "estimate": {
              "id": 697,
              "route": "/estimate",
              "proxy_settings": {
                "x-zengine-webhook-key": "astringsolongnomeremortalcouldtellitsvalue"
                // you'll notice no port given for this service, defaults to 3000
              }
            }
          },
          "proxy_settings": { // plugin-level proxy settings
            "x-firebase-url": "https://some-url-im-not-comfortable-unveiling.firebaseio.com/",
            "x-firebase-secret": "correspondingsecretforfirebase"
          }
        }
      },
      "default": true
    },
    "prod": {
      "access_token": "secretprodkey",
      "plugins": {
        "wsos-graduated-within": {
          "route": "/wsosgraduatedwithin2",
          "namespace": "wsosGraduatedWithin2",
          "id": 916,
          "services": {
            "update": {
              "id": 288,
              "route": "/update"
            }
          }
        }
      }
    }
  },
  "proxy_settings": { // top-level proxy settings
    "subdomain": "", // Chris, please test this lol
    "authtoken": "",
    "ngrokPort": 0 // 0 will be ignored and default to 5050, btw
  }
}
```

I will be back at it later on to create a video demonstrating its use, and full documentation will be coming out over the next few days. But, right now I'm going to go paint some shelves for my wife's birthday that was last month 🤦🏼‍♂️. Looking forward to seeing this get into everyone's backend service development workflow. I think it will make a big difference.

### CODE REVIEW

**Comment by evert0n** [comment]
@tedkulp can you let us know when this final, I will wait to test

**Comment by tedkulp** [comment]
I have it quick look and it seems ok so far.  I might try to test it a bit today if time permits, but I'm ok with it moving forward.

**Comment by tehpsalmist** [comment]
As far as I can tell, it won't break anything that existed previously at this point (Anna found one that we fixed), so if you wanted to merge it, that's cool with me. I just felt it needed some preliminary battle testing because it was a lot of code and there were some known quirks, that I listed above.

**Comment by evert0n** [comment]
@tehpsalmist for #1 I believe you can hook into the `process` to clean that up or even `http-proxy` and `ngrok` should have events that detect it

**Comment by evert0n** [comment]
@tehpsalmist 2 what about using saving into a log file, at least you can access or `tail -f` it

**Comment by tehpsalmist** [comment]
@evert0n That is a really interesting suggestion about logging to a file. I would be curious how you might do that in a way that maintains easy access to relevant information and also doesn't leave a ton of junk in the user's filesystem. I am game for giving it a try, for sure, though!

About the events and such, the only real "concern" is that somehow the individual backend service wouldn't be properly shutdown, leaving that port in use. Like I mentioned, I haven't seen that error yet with the most recent version of the code, but I did encounter it early on, without a very good explanation as to why that happened and how to definitely avoid it. ngrok and http-proxy always shut down without a problem. I need to make that video I promised for you guys to give a rundown of how things currently work and where those minor quirks show up.

**Comment by evert0n** [comment]
@tehpsalmist if I understood the issue with the watch eating up information from the ngrok, I was suggesting just to log that part and won't have issue if you clean up the file on each start.

**Comment by tehpsalmist** [comment]
Ok, I see. Where would you store the file? Maybe at the top of maya_build?

**Pull request merged**
